version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - /packages/db/.env
      - /apps/user-app/.env
